### ISSUE TITLE
Add argument to print future change

### ISSUE THREAD

**Issue by lansman** [peritus/bumpversion#102]
That only prints useful message, do nothing more.
```
user@comp> bumpversion patch --print-change patch
  version will change from 0.2.1 to 0.2.2
user@comp> bumpversion patch --print-change patch  # again got the same
  version will change from 0.2.1 to 0.2.2
user@comp> bumpversion patch --tag --commit 
user@comp> bumpversion patch --print-change patch
  version will change from 0.2.2 to 0.2.3
```

**Comment by peritus** [comment]
Wouldn't

```bumpversion --verbose --dry-run | grep $WHAT_YOURE_INTERESTED_IN```

work for you ?

**Comment by lansman** [comment]
Probably it works, but it isn't much covenient, also there is no built-in grep command in Windows... It would be better to have such a command, i suppose.

**Comment by peritus** [comment]
Looks like there is `findstr` on windows: https://superuser.com/questions/300815/grep-equivalent-for-windows-7 (idk, just googled it).

Bumpversion is meant to be used together with other programs.
