### ISSUE TITLE
tests are missing pypi

### ISSUE THREAD

**Issue by jlec** [peritus/bumpversion#108]
Could you please include the tests in the package on pypi so that downstream Distro maintainers can implement test phases while installing the package?

**Comment by peritus** [comment]
Yes, will do that. Looking forward to an ebuild then :)

**Comment by jlec** [comment]
It has already been commited some hours ago :)

**Comment by peritus** [comment]
The fix in c1808f79a8a569cca93b50bed4188997f39ca567 includes the tests in the tarball, however they won't be installed when using `pip install bumpversion` from the next version on.

Let me know if that works from your perspective as a gentoo package maintainer.

Thanks you for bringing this up!

**Comment by jlec** [comment]
Thanks. Should work that way.
