### ISSUE TITLE
Commit all changes before tagging

### ISSUE THREAD

**Issue by walidsa3d** [peritus/bumpversion#115]
It would be nice to add an option to commit all changes before tagging (instead of some specific files).

**Comment by peritus** [comment]
How about

```
git commit -av
bumpversion patch
```

.. would that work for you ?

**Comment by walidsa3d** [comment]
bumpversion makes changes that need to be commited too

**Comment by peritus** [comment]
Yes, the commands I posted would result in two commits.

I'm having a hard time here grasping what you want from your two sentences. Can you elaborate a little ?

**Comment by walidsa3d** [comment]
Exactly, I don't want to pollute my commit history with commits that contain only changes to setup.py and setup.cfg.  I want a workflow like this:
-Bump version (in files)
-Commit all
-Tag

**Comment by peritus** [comment]
That sounds very similar to #38 .. could you go over there and have a look whether my proposals there would also fit your usecase ? If not, could you comment there what your usecase would need ?

Thanks for bringing this up :)
