### ISSUE TITLE
Use annotated tags

### ISSUE THREAD

**Issue by cmeeren** [peritus/bumpversion#116]
Everything I've read about tags (see e.g. [this, and links therein](http://stackoverflow.com/a/26438076/2978652)) says to use annotated tags for "official" non-private tags like version numbers/releases, and lightweight tags only for private stuff. Bumpversion uses lightweight tags. I suggest changing to annotated tags as per recommendations.

**Comment by cmeeren** [comment]
It seems there has been a PR for this for some time (#58). Any reason it hasn't been merged?

**Comment by peritus** [comment]
Yes, duplicate of #58. Hasn't been merged yet because I haven't had the chance to do so.
