### ISSUE TITLE
Add [skip ci] to default commit message

### ISSUE THREAD

**Issue by m3nu** [peritus/bumpversion#141]
I just struggled to bump, tag and commit after a CircleCI test without having it run again on that commit.

Later I found `[skip ci]` which supported by [CircleCI](https://circleci.com/docs/skip-a-build/), [Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Ci+Skip+Plugin) and [Travis](https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build)

So it would be useful to add `[skip ci]` to the commit message, I suppose?

**Comment by ulope** [comment]
Please don't.

We (and I know of more projects doing this) use travis to automate releases to PyPI if all tests pass on tagged commits so we depend on those commits being executed by CI.

**Comment by peritus** [comment]
Yes, bumpversion won't force you into workflows. If you like a commit message other then the default, please configure it.

**Comment by chfast** [comment]
How can I have a multiline commit message in config?
