### ISSUE TITLE
[FEATURE] Git\Mercurial Branch Creation

### ISSUE THREAD

**Issue by galvinograd** [peritus/bumpversion#148]
We are working according to [gitflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) methology, and therefore we must create a new branch for each release.

I suggest to implement the following mechanism:
Adding two new parameters:
- "branch" - a flag that tells if a branch should be created (similar to "tag" or "commit"). This flag will require the presence of the commit flag.
- "branch_name" - a string parameter that describes the desired name of the branch (similar to "tag_name").

I think many users will benefit from this feature. As a side note, I have not problem implementing it :)

**Comment by peritus** [comment]
Sorry, this is outside of the scope of this project.
Bumpversion aims to bump versions, not to become a second gitflow implementation.
