### ISSUE TITLE
bumpversion rewrites setup.cfg file

### ISSUE THREAD

**Issue by wrobell** [peritus/bumpversion#171]
bumpversion rewrites setup.cfg file. It would be great if it just changed the version without doing that.

**Comment by peritus** [comment]
It doesn't due to a technical limitation with the parser it uses. You can use `.bumpversion.cfg` as an alternative.

**Comment by wrobell** [comment]
I believe only version is changed, so why not simply use regexp like with other files (which I believe is being done).
