### ISSUE TITLE
Only bump specific pattern without matching other versions of like pattern in file

### ISSUE THREAD

**Issue by milkshoes** [peritus/bumpversion#178]
I'm sorry in advance if this is described in the documentation somewhere. I didn't quite see the exact scenario I'm encountering described in the "_search =_" section or the "_Python Format String Syntax_" and haven't been able to get what I need to work.

**My need is this:**
I have a bumpversion config file as listed below. However, I need it to only bump a specific match and only that match in a file because we could potentially have one or many similar patterns with the same number occur and it's currently replacing all of them throughout the file which is not the desired result.

The desired result is to only change the '_version := "6.26.0_"' and **NOT** the '_scalaVersion := "6.26.0_"'. My current search = pattern is affecting both versions when the numbers match and that is not usable.

Any help is greatly appreciated and thank you!

**My current .bumpversion.cfg:**

```
[bumpversion]
current_version = 6.26.0

[bumpversion:file:build.sbt]
search = "version := {current_version}"
replace = {new_version}
```

**The file with potential bumping conflicts:**

```
name := "my-test-file-for-bumping"

version := "6.26.0" // This is the only one that should be "bumped"

scalaVersion := "6.26.0" // This shouldn't match!

whateverVersion  := "6.26.0" // This too shouldn't match!

libraryDependencies ++= Seq(
  javaJdbc,
  filters,
  "commons-collections" % "commons-collections"           % "3.2.1",
  "org.apache.tika"     % "tika-core"                     % "1.13",
  "org.apache.tika"     % "tika-parsers"                  % "1.13",
  "junit"               % "junit"                         % "4.12"      % "test"
)

publishMavenStyle := true
```

**Comment by arcanefoam** [comment]
As your current files are there is no way that you can differentiate between your project version and matching versions of dependencies. What works in this situation is to eliminate the conflicts by adding a comment to the line with the version you want to bump, e.g. //bmp version.

Then add this extra comment to both the search and replace expressions in bumpversion configuration.

Note that trying to make bumpversion smarter, aka match first, match a specific line number, etc., will actually make it harder to use IMHO.

**Comment by arcanefoam** [comment]
Hi, 
Using your "demo" files I modified them and this works for me:
**.bumpversion.cfg**
`
[bumpversion]
current_version = 6.26.0

[bumpversion:file:bumpfile.txt]
search = version := "{current_version}" //PACKAGE VERSION HERE
replace = version := "{new_version}" //PACKAGE VERSION HERE
`
**bumpfile.txt**
`
name := "my-test-file-for-bumping"

version := "6.26.0" //PACKAGE VERSION HERE

scalaVersion := "6.26.0" // This shouldn't match!

whateverVersion  := "6.26.0" // This too shouldn't match!

libraryDependencies ++= Seq(
  javaJdbc,
  filters,
  "commons-collections" % "commons-collections"           % "3.2.1",
  "org.apache.tika"     % "tika-core"                     % "1.13",
  "org.apache.tika"     % "tika-parsers"                  % "1.13",
  "junit"               % "junit"                         % "4.12"      % "test"
)

publishMavenStyle := true
`

**Comment by milkshoes** [comment]
Thanks, your version works for me. Thought I had tried that combination as one of my tests with no luck. Must have been pebkac.
