### ISSUE TITLE
tag name contains double quotes

### ISSUE THREAD

**Issue by AlaaAttya** [peritus/bumpversion#191]
```
[bumpversion]
current_version = 1.0.2
commit = True
tag = True
tag_name = "v{new_version}"
```

when using the following config file it ends up adding double quotes around tag name in the releases
 like this `"v1.0.0"` instead of `v1.0.0`

**Comment by peritus** [comment]
Remove the double quotes in the config file maybe ?

**Comment by AlaaAttya** [comment]
if i use this `tag_name = v{new_version}` it shows this error

```
Git working directory is not clean:
M .bumpversion.cfg

Use --allow-dirty to override this if you know what you're doing.
Traceback (most recent call last):
  File "/usr/local/bin/bumpversion", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bumpversion/__init__.py", line 897, in main
    vcs.assert_nondirty()
  File "/usr/local/lib/python2.7/site-packages/bumpversion/__init__.py", line 109, in assert_nondirty
    b"\n".join(lines)))
bumpversion.WorkingDirectoryIsDirtyException

```

**Comment by AlaaAttya** [comment]
@peritus are you able to reproduce it?

**Comment by SitiSchu** [comment]
@AlaaAttya The reason you're getting that error is because you edited your `.bumpversion.cfg` and didnt commit the changes. Commit your changes and try again.

**Comment by AlaaAttya** [comment]
@SitiSchu your trick got my issue fixed, thanks a million :)
