### ISSUE TITLE
Release version 0.5.1 (?)

### ISSUE THREAD

**Issue by thomasf** [peritus/bumpversion#66]
f0baac82b4bbd17fff9e5f7913ec03ccbc8dad22  is kind of needed to do semver properly. It would be nice if that was available in a release version

**Comment by peritus** [comment]
You're right. Let's do release early release often again.

**Comment by peritus** [comment]
Here you go:

https://pypi.python.org/pypi/bumpversion/0.5.1

Thanks for nudging me.

**Comment by thomasf** [comment]
Great, thanks.
