### ISSUE TITLE
Bug: bumpversion makes/overwrites the keys in setup.cfg in lowercase

### ISSUE THREAD

**Issue by theskumar** [peritus/bumpversion#75]
`setup.cfg` (Before)
```
[bumpversion]
current_version = 0.1.0

[other]
DJANGO_SETTINGS = Value
```

`setup.cfg` running `bumpversion patch`
```
[bumpversion]
current_version = 0.1.1

[other]
django_settings = Value
```

We moved the `.bumpversion.cfg` to `setup.cfg` which already had other sections. bumping up a new version makes all the keys in `setup.cfg` lowercase making them unusable. @peritus thoughts?

**Comment by peritus** [comment]
Interesting. Keep using .bumpversion.cfg as a workaround, I'll look into it.

**Comment by theskumar** [comment]
Sure and thanks!

**Comment by peritus** [comment]
That should be fixed now, thanks again for the report.

I'll come say hello, next time I'm in New Delhi and you show me the Python community in India ?

**Comment by theskumar** [comment]
Hey @peritus, sure any time, would love to do that. We also have Pycon India 2015 coming up. http://in.pycon.org/2015/. You might wanna plan something around that timeline.

 Just drop me an email or i'm available [@_theskumar](http://twitter.com/_theskumar)

**Comment by peritus** [comment]
Thanks! Will be in India probably around this time next year, backpacking with my girlfriend. We're currently learning some hindi and need to finish a university graduation, but after that India is our first stop!

I'll reach out to you, even if only for a coffee in New Delhi.

**Comment by theskumar** [comment]
sure thing :)

**Comment by theskumar** [comment]
@peritus since this was a patch/fix wondering if we can have a [new release](https://github.com/peritus/bumpversion/compare/v0.5.1...master) 0.5.2, so we are able to install it via pypi.

Thanks,
