### ISSUE TITLE
Missing code tests

### ISSUE THREAD

**Issue by lgiordani** [peritus/bumpversion#91]
The whole test suite lacks tests of the code structures (such as VersionPart or ConfiguredVersionPartConfiguration). May I add some tests on those classes? it is always useful to have some basic behaviour tests.

Moreover, in another issue I'm going to propose some changes to these structures so this could allow to spot subtle errors.

**Comment by peritus** [comment]
Now that #98 is merged, this can be closed ? I haven't checked coverage, but if you feel confident with it, @lgiordani please feel free to close this.

**Comment by lgiordani** [comment]
Absolutely. There is probably still some areas to test, but given the refactoring we are doing I'd say this issue served its purpose. Thanks
