### ISSUE TITLE
VersionPart configuration 

### ISSUE THREAD

**Issue by lgiordani** [peritus/bumpversion#92]
I'd like to merge the NumericVersionPartConfiguration and the ConfiguredVersionPartConfiguration classes to simplify the internal structure of the program.

NumericVersionPartConfiguration is a special case of ConfiguredVersionPartConfiguration, so this is easy and gets rid of some intricacies such as that of ThisVersionPartConfiguration.

**Comment by peritus** [comment]
Also fixed in #98, @lgiordani ? I think we can also close this then.

**Comment by lgiordani** [comment]
Exactly, thanks!
