### ISSUE TITLE
bumpversion must be installed to run tests

### ISSUE THREAD

**Issue by lgiordani** [peritus/bumpversion#94]
Some of the tests in tests.py require bumpversion to be installed (e.g. test_usage_string_fork()). Is possibile to avoid this? main() is already imported and some tests make use of it (e.g. test_usage_string()).
It is not totally wrong, but creates a strange circular reference in the package.

**Comment by peritus** [comment]
I think tox already takes care of that the `bumpversion` command that is called is in fact the one that is in the directory, not a globally installed one.

I'll have to reproduce this with a clean vagrant box.

**Comment by peritus** [comment]
Hey so, yes, I introduced these tests after releasing a broken bumpversion where everything (and all the tests) worked, except `__main__`.  So these tests also exist to make sure `setup.py` works as expected.

When hacking on bumpversion, a simple `bin/pip install -e .` inside a virtualenv should do the trick.

Please re-open if you disagree.
